Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2022-05, with the labels that each got.

#860 Set page title for Calculated summary blocks
  app/views/contexts/calculated_summary_context.py
  app/views/handlers/calculated_summary.py
  tests/functional/spec/features/calculated_summary.spec.js
Labels: Bug Fix

#862 Bug fix: Support for in-flight sessions that use survey_url
  app/data_models/session_data.py
  tests/app/data_model/test_session_data.py
  tests/app/data_model/test_session_store.py
Labels: Bug Fix

#854 Ability to return to calculated summary
  app/questionnaire/router.py
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/summary/answer.py
  app/views/contexts/summary/block.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary/question.py
  app/views/handlers/block.py
  app/views/handlers/question.py
  tests/app/questionnaire/test_router.py
  tests/app/views/contexts/summary/test_answer.py
  tests/app/views/contexts/test_calculated_summary_context.py
  tests/functional/spec/features/calculated_summary.spec.js
Labels: New Feature

#858 Add failed requests handling and retries for survey url
  app/utilities/schema.py
  tests/app/utilities/test_schema.py
  tests/integration/integration_test_case.py
  tests/integration/session/test_login.py
Labels: Enhancement

#859 Add section enabled rules from previous sections in when rules
  app/questionnaire/path_finder.py
  app/questionnaire/router.py
  schemas/test/en/test_new_routing_and_skipping_section_dependencies.json
  tests/functional/spec/routing_and_skipping_section_dependencies.spec.js
Labels: Bug Fix

#848 Rules require dependent section routing path re-evaluation
  app/questionnaire/path_finder.py
  app/questionnaire/questionnaire_schema.py
  app/questionnaire/questionnaire_store_updater.py
  app/views/handlers/block.py
  app/views/handlers/question.py
  tests/app/questionnaire/conftest.py
  tests/app/questionnaire/test_questionnaire_schema.py
  tests/app/questionnaire/test_questionnaire_store_updater.py
  tests/functional/spec/routing_and_skipping_section_dependencies.spec.js
Labels: Bug Fix

#866 Add type hinting to secrets
  app/secrets.py
  mypy.ini
  tests/integration/routes/test_feedback.py
Labels: technical-debt

#874 Update to Design System version 50
  .design-system-version
  package.json
  templates/partials/question.html
  yarn.lock
Labels: Bug Fix

#870 Update DS version to v50
  .design-system-version
  package.json
  templates/partials/question.html
  yarn.lock
Labels: Bug Fix
