Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2022-08, with the labels that each got.

#908 Update DS version for label font weight bug fix
  .design-system-version
Labels: Bug Fix

#900 Remove metadata from session
  app/authentication/authenticator.py
  app/data_models/session_data.py
  app/helpers/language_helper.py
  app/helpers/schema_helpers.py
  app/helpers/template_helpers.py
  app/routes/dump.py
  app/routes/flush.py
  app/routes/individual_response.py
  app/routes/questionnaire.py
  app/routes/session.py
  app/setup.py
  app/utilities/schema.py
  app/views/contexts/thank_you_context.py
  app/views/handlers/confirm_email.py
  app/views/handlers/feedback.py
  app/views/handlers/thank_you.py
  tests/app/conftest.py
  tests/app/data_model/test_session_store.py
  tests/app/helpers/test_schema_helper.py
  tests/app/utilities/test_schema.py
  tests/app/views/contexts/conftest.py
  tests/app/views/contexts/test_thank_you_context.py
  tests/app/views/handlers/conftest.py
  tests/app/views/handlers/test_confirmation_email_fulfilment_request.py
Labels: Enhancement

#916 Fix yarn typescript warning
  package.json
  yarn.lock
Labels: dependencies

#903 Fix DAC issue summary table headers
  app/translations/messages.pot
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/section_summary_context.py
  app/views/contexts/summary_context.py
  package.json
  templates/partials/summary/collapsible-summary.html
  templates/partials/summary/summary.html
  tests/app/views/contexts/test_calculated_summary_context.py
  tests/app/views/contexts/test_section_summary_context.py
  tests/app/views/contexts/test_submitted_response_context.py
  tests/integration/questionnaire/test_questionnaire_content_variants.py
  tests/integration/questionnaire/test_questionnaire_submit.py
  tests/integration/routes/test_view_submitted_response.py
  yarn.lock
Labels: Bug Fix
