Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2023-10, with the labels that each got.

#1214 Add type hints to fields module
  app/forms/field_handlers/address_handler.py
  app/forms/field_handlers/date_handlers.py
  app/forms/field_handlers/dropdown_handler.py
  app/forms/field_handlers/duration_handler.py
  app/forms/field_handlers/mobile_number_handler.py
  app/forms/field_handlers/number_handler.py
  app/forms/field_handlers/select_handlers.py
  app/forms/field_handlers/string_handler.py
  app/forms/field_handlers/text_area_handler.py
  app/forms/fields/date_field.py
  app/forms/fields/decimal_field_with_separator.py
  app/forms/fields/integer_field_with_separator.py
  app/forms/fields/max_text_area_field.py
  app/forms/fields/month_year_date_field.py
  app/forms/fields/multiple_select_field_with_detail_answer.py
  app/forms/fields/select_field_with_detail_answer.py
  app/forms/fields/year_date_field.py
  app/forms/validators.py
  app/utilities/types.py
  mypy.ini
  tests/app/forms/field_handlers/conftest.py
  tests/app/forms/fields/test_date_field.py
  tests/app/forms/fields/test_month_year_date_field.py
  tests/app/forms/fields/test_year_date_field.py
  tests/app/forms/test_custom_fields.py
Labels: help wanted

#1210 Grand calculated summary inside a repeating section
  app/data_models/list_store.py
  app/questionnaire/router.py
  app/utilities/strings.py
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/grand_calculated_summary_context.py
  app/views/contexts/summary/answer.py
  app/views/contexts/summary/block.py
  app/views/contexts/summary/calculated_summary_block.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary/question.py
  app/views/handlers/block.py
  app/views/handlers/calculation_summary.py
  app/views/handlers/question.py
  schemas/test/en/test_grand_calculated_summary_inside_repeating_section.json
  tests/app/data_model/test_list_store.py
  tests/app/questionnaire/conftest.py
  tests/app/questionnaire/test_router.py
  tests/app/utilities/test_strings.py
  tests/app/views/contexts/summary/test_answer.py
  tests/functional/spec/features/grand_calculated_summary/grand_calculated_summary_inside_repeating_section.spec.js
  tests/integration/questionnaire/test_questionnaire_grand_calculated_summary.py
Labels: New Feature

#1225 Add UKHSA ONS theme
  app/helpers/template_helpers.py
  app/survey_config/__init__.py
  app/survey_config/social_survey_config.py
  app/survey_config/survey_type.py
  schemas/test/en/test_theme_ukhsa_ons.json
  templates/assets/images/ons-logo-stacked.svg
  templates/assets/images/ukhsa-logo-stacked.svg
  templates/errors/_base.html
  tests/app/helpers/test_template_helpers.py
  tests/functional/spec/theme_ukhsa_ons.spec.js
Labels: New Feature

#1215 Feat: Grand calculated summary value sources
  app/questionnaire/placeholder_transforms.py
  app/questionnaire/value_source_resolver.py
  schemas/test/en/test_grand_calculated_summary_inside_repeating_section.json
  schemas/test/en/test_grand_calculated_summary_repeating_answers.json
  tests/app/questionnaire/test_value_source_resolver.py
  tests/functional/spec/features/grand_calculated_summary/grand_calculated_summary_inside_repeating_section.spec.js
  tests/functional/spec/features/grand_calculated_summary/grand_calculated_summary_repeating_answers.spec.js
  tests/integration/questionnaire/test_questionnaire_grand_calculated_summary.py
Labels: New Feature

#1229 Create ReturnLocation object to store return params
  app/questionnaire/return_location.py
  app/questionnaire/router.py
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/grand_calculated_summary_context.py
  app/views/contexts/section_summary_context.py
  app/views/contexts/summary/answer.py
  app/views/contexts/summary/block.py
  app/views/contexts/summary/calculated_summary_block.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary/list_collector_base_block.py
  app/views/contexts/summary/list_collector_block.py
  app/views/contexts/summary/list_collector_content_block.py
  app/views/contexts/summary/question.py
  app/views/handlers/block.py
  app/views/handlers/calculation_summary.py
  app/views/handlers/list_action.py
  app/views/handlers/list_add_question.py
  app/views/handlers/list_collector.py
  app/views/handlers/list_edit_question.py
  app/views/handlers/list_repeating_question.py
  app/views/handlers/primary_person_question.py
  app/views/handlers/question.py
  app/views/handlers/relationships/relationship_question.py
  tests/app/questionnaire/test_return_location.py
  tests/app/questionnaire/test_router.py
  tests/app/views/contexts/summary/test_answer.py
  tests/app/views/contexts/summary/test_block.py
  tests/app/views/contexts/summary/test_question.py
  tests/app/views/contexts/test_calculated_summary_context.py
  tests/app/views/contexts/test_grand_calculated_summary_context.py
Labels: help wanted

#1232 Remove question text from GA event
  templates/partials/introduction/preview.html
Labels: Bug Fix
