Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2023-11, with the labels that each got.

#1246 Add support for CIR
  .development.env
  .functional-tests.env
  README.md
  app/data_models/metadata_proxy.py
  app/routes/flush.py
  app/routes/individual_response.py
  app/routes/questionnaire.py
  app/routes/session.py
  app/settings.py
  app/submitter/converter_v2.py
  app/utilities/bind_context.py
  app/utilities/metadata_parser_v2.py
  app/utilities/schema.py
  tests/app/parser/test_metadata_parser.py
  tests/app/questionnaire/conftest.py
  tests/app/submitter/conftest.py
  tests/app/submitter/test_converter.py
  tests/app/utilities/conftest.py
  tests/app/utilities/test_schema.py
  tests/integration/create_token.py
  tests/integration/session/test_login.py
  tests/integration/test_flush_data.py
Labels: New Feature

#1266 Add no return_to_answer_id handling when generating return_to for calculated summary
  app/questionnaire/router.py
  schemas/test/en/test_validation_sum_against_value_source.json
  tests/app/questionnaire/test_questionnaire_schema.py
  tests/app/questionnaire/test_router.py
  tests/functional/spec/features/validation/sum/value_source.spec.js
Labels: Bug Fix

#1253 Add confirmation email support to non census thank-you page
  app/translations/messages.pot
  app/views/contexts/email_form_context.py
  app/views/contexts/thank_you_context.py
  app/views/handlers/thank_you.py
  schemas/test/en/test_confirmation_email.json
  schemas/test/en/test_feedback_email_confirmation.json
  templates/census-thank-you.html
  templates/confirmation-email.html
  templates/partials/confirmation-email-form.html
  templates/thank-you.html
  tests/functional/spec/confirmation_email.spec.js
  tests/functional/spec/exit.spec.js
  tests/integration/questionnaire/test_questionnaire_schema_theme_thank_you.py
  tests/integration/routes/test_confirmation_email.py
Labels: Enhancement
