Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2023-08, with the labels that each got.

#1174 Remove non-JS GA
  app/setup.py
  templates/layouts/_base.html
  tests/integration/test_app_create.py
  tests/integration/test_application_variables.py
Labels: Bug Fix

#1173 Using supplementary data list items
  app/data_models/supplementary_data_store.py
  app/questionnaire/placeholder_transforms.py
  app/questionnaire/value_source_resolver.py
  schemas/test/en/test_supplementary_data.json
  scripts/mock_data/supplementary_data.json
  scripts/mock_data/supplementary_data_no_repeat.json
  scripts/mock_data/supplementary_data_no_repeat_v2.json
  scripts/mock_data/supplementary_data_v2.json
  scripts/mock_data/supplementary_data_with_repeat.json
  scripts/mock_data/supplementary_data_with_repeat_v2.json
  scripts/mock_data/supplementary_dataset_metadata_response.json
  scripts/mock_data/supplementary_dataset_metadata_response_non_repeating_items.json
  scripts/mock_data/supplementary_dataset_metadata_response_repeating_items.json
  scripts/mock_sds_endpoint.py
  tests/app/conftest.py
  tests/app/data_model/test_supplementary_data_store.py
  tests/app/questionnaire/rules/test_rule_evaluator.py
  tests/app/questionnaire/test_placeholder_transforms.py
  tests/app/questionnaire/test_value_source_resolver.py
  tests/functional/generate_pages.py
  tests/functional/helpers.js
  tests/functional/spec/features/calculated_summary/new_calculated_summary_repeating_and_static_answers.spec.js
  tests/functional/spec/features/repeating_blocks/list_collector_repeating_blocks.spec.js
  tests/functional/spec/features/supplementary_data/supplementary_data.spec.js
  tests/functional/spec/features/supplementary_data/supplementary_data_non_list_items.spec.js
  tests/functional/spec/features/validation/sum/dynamic.spec.js
  tests/integration/questionnaire/test_questionnaire_supplementary_data_non_list_items.py
Labels: New Feature

#1179 Update CSP policy urls for GA4
  app/setup.py
  tests/integration/test_app_create.py
Labels: Bug Fix

#1178 Update valid units and remove metric ton support
  app/jinja_filters.py
  schemas/test/en/test_placeholder_transform.json
  schemas/test/en/test_unit_patterns.json
  tests/app/test_jinja_filters.py
  tests/functional/spec/features/units.spec.js
  tests/integration/questionnaire/test_questionnaire_locale.py
Labels: Breaking Change

#1172 Authenticate SDS Requests with GCP
  .development.env
  .functional-tests.env
  Pipfile
  Pipfile.lock
  app/oidc/__init__.py
  app/oidc/gcp_oidc.py
  app/oidc/local_oidc.py
  app/oidc/oidc.py
  app/services/supplementary_data.py
  app/settings.py
  app/setup.py
  tests/app/oidc/__init__.py
  tests/app/oidc/test_gcp_oidc.py
  tests/app/services/test_request_supplementary_data.py
  tests/integration/test_app_create.py
Labels: Enhancement

#1186 Grand Calculated Summary with repeating answers
  app/questionnaire/router.py
  app/views/handlers/list_repeating_question.py
  schemas/test/en/test_grand_calculated_summary_multiple_sections.json
  schemas/test/en/test_grand_calculated_summary_repeating_answers.json
  tests/app/questionnaire/conftest.py
  tests/app/questionnaire/test_router.py
  tests/functional/spec/features/grand_calculated_summary/grand_calculated_summary_multiple_sections.spec.js
  tests/functional/spec/features/grand_calculated_summary/grand_calculated_summary_repeating_answers.spec.js
  tests/integration/questionnaire/test_questionnaire_grand_calculated_summary.py
Labels: Enhancement

#1184 Bug Fix: Editing list items 404 when using multiple list collectors with repeating blocks
  app/views/handlers/list_edit_question.py
  app/views/handlers/list_repeating_question.py
  schemas/test/en/test_list_collector_repeating_blocks_with_hub.json
  tests/functional/spec/features/repeating_blocks/list_collector_repeating_blocks.spec.js
  tests/integration/questionnaire/test_questionnaire_list_collector_repeating_blocks.py
Labels: Bug Fix

#1183 Bug Fix: Schemas with dynamic answers blocks in separate section to the list collector not loading
  app/questionnaire/questionnaire_schema.py
  app/questionnaire/questionnaire_store_updater.py
  app/questionnaire/value_source_resolver.py
  app/views/contexts/summary/list_collector_block.py
  schemas/test/en/test_dynamic_answers_list_source.json
  tests/app/questionnaire/test_questionnaire_schema.py
  tests/functional/spec/features/dynamic_answers_list_value_source.spec.js
Labels: Bug Fix

#1138 Bug Fix: `get_width_for_number` function when using value sources
  app/jinja_filters.py
  app/questionnaire/questionnaire_schema.py
  schemas/test/en/test_numbers.json
  tests/app/questionnaire/conftest.py
  tests/app/questionnaire/test_questionnaire_schema.py
  tests/app/test_jinja_filters.py
  tests/functional/spec/numbers.spec.js
  tests/functional/spec/save_sign_out.spec.js
Labels: Bug Fix

#1156 Add list collector content pages
  app/forms/questionnaire_form.py
  app/jinja_filters.py
  app/questionnaire/questionnaire_schema.py
  app/questionnaire/router.py
  app/views/contexts/list_context.py
  app/views/contexts/section_summary_context.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary/list_collector_base_block.py
  app/views/contexts/summary/list_collector_block.py
  app/views/contexts/summary/list_collector_content_block.py
  app/views/handlers/block.py
  app/views/handlers/block_factory.py
  app/views/handlers/list_action.py
  app/views/handlers/list_collector.py
  app/views/handlers/list_collector_content.py
  app/views/handlers/list_repeating_question.py
  app/views/handlers/question.py
  schemas/test/en/test_list_collector_content_page.json
  templates/listcollectorcontent.html
  templates/partials/block.html
  tests/app/test_jinja_filters.py
  tests/functional/generate_pages.py
  tests/functional/spec/list_collector_content.spec.js
  tests/integration/questionnaire/test_questionnaire_list_collector_content.py
Labels: New Feature

#1192 Bind Contextvars before metadata is parsed
  app/routes/session.py
Labels: Enhancement
