Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2023-02, with the labels that each got.

#1018 Bug Fix logger values not being bound to logs
  Pipfile
  Pipfile.lock
  application.py
Labels: Bug Fix

#1004 Add type hinting to context
  app/questionnaire/placeholder_renderer.py
  app/questionnaire/questionnaire_schema.py
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/confirm_email_context.py
  app/views/contexts/context.py
  app/views/contexts/email_form_context.py
  app/views/contexts/feedback_form_context.py
  app/views/contexts/hub_context.py
  app/views/contexts/list_context.py
  app/views/contexts/question.py
  app/views/contexts/section_summary_context.py
  app/views/contexts/submission_metadata_context.py
  app/views/contexts/summary/answer.py
  app/views/contexts/summary/block.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary/list_collector_block.py
  app/views/contexts/summary/question.py
  app/views/contexts/summary_context.py
  app/views/contexts/thank_you_context.py
  app/views/contexts/view_submitted_response_context.py
  mypy.ini
Labels: Enhancement

#1015 Add support for answer codes in runner
  app/submitter/converter_v2.py
  schemas/test/en/test_answer_codes.json
  schemas/test/en/test_list_collector_section_summary.json
  tests/app/submitter/test_convert_payload_0_0_3.py
Labels: New Feature

#1020 Bug: Flush always using v1 converter
  app/routes/flush.py
  tests/integration/test_flush_data.py
Labels: Bug Fix

#1008 Update Ubuntu to version 22
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/codeql-analysis.yml
Labels: dependencies

#1003 Fix bug: add to list is returning straight back to summary
  app/questionnaire/router.py
  app/views/handlers/list_action.py
  app/views/handlers/list_add_question.py
  app/views/handlers/list_collector.py
  app/views/handlers/list_remove_question.py
  app/views/handlers/question.py
  schemas/test/en/test_list_collector_section_summary.json
  tests/functional/spec/features/repeating_sections/repeating_sections_with_hub_and_spoke.spec.js
  tests/functional/spec/list_collector.spec.js
  tests/functional/spec/list_collector_section_summary.spec.js
  tests/integration/questionnaire/test_questionnaire_list_change_evaluates_sections.py
  tests/integration/questionnaire/test_questionnaire_list_collector.py
Labels: Bug Fix

#1013 Split tests into matrix suites
  .github/workflows/pull_request.yml
  tests/functional/spec/timeout/timeout_modal.js
  tests/functional/spec/timeout/timeout_modal.spec.js
  tests/functional/spec/timeout/timeout_modal_expired/timeout_modal_expired.spec.js
  tests/functional/spec/timeout/timeout_modal_expired/timeout_modal_post_submission_expired.spec.js
  tests/functional/spec/timeout/timeout_modal_extended/timeout_modal_extended.spec.js
  tests/functional/spec/timeout/timeout_modal_extended/timeout_modal_post_submission_extended.spec.js
  tests/functional/spec/timeout/timeout_modal_extended_new_window/timeout_modal_extended_new_window.spec.js
  tests/functional/spec/timeout/timeout_modal_extended_new_window/timeout_modal_post_submission_extended_new_window.spec.js
  tests/functional/spec/timeout/timeout_modal_post_submission.spec.js
  tests/functional/wdio.conf.js
Labels: Enhancement

#1037 Bug: Runner page width set to 12 columns
  templates/layouts/_base.html
  tests/functional/spec/page_layout.spec.js
Labels: Bug Fix

#1024 Update Runner logger binds to use contextvars and unpin dependencies
  .pylintrc
  Pipfile
  Pipfile.lock
  app/authentication/authenticator.py
  app/cloud_tasks/cloud_task_publishers.py
  app/forms/field_handlers/date_handlers.py
  app/forms/fields/decimal_field_with_separator.py
  app/forms/fields/integer_field_with_separator.py
  app/forms/fields/multiple_select_field_with_detail_answer.py
  app/forms/fields/select_field_with_detail_answer.py
  app/forms/questionnaire_form.py
  app/forms/validators.py
  app/helpers/template_helpers.py
  app/jinja_filters.py
  app/questionnaire/path_finder.py
  app/questionnaire/placeholder_parser.py
  app/questionnaire/placeholder_transforms.py
  app/questionnaire/questionnaire_store_updater.py
  app/questionnaire/when_rules.py
  app/routes/errors.py
  app/routes/flush.py
  app/routes/individual_response.py
  app/routes/questionnaire.py
  app/routes/session.py
  app/secrets.py
  app/settings.py
  app/setup.py
  app/submitter/converter.py
  app/survey_config/census_config.py
  app/utilities/schema.py
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/section_summary_context.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary/list_collector_block.py
  app/views/contexts/summary/question.py
  app/views/contexts/summary_context.py
  app/views/handlers/__init__.py
  app/views/handlers/confirm_email.py
  app/views/handlers/confirmation_email.py
  app/views/handlers/feedback.py
  application.py
  profile_application.py
  tests/app/data_model/conftest.py
  tests/app/data_model/test_session_store.py
  tests/app/forms/test_questionnaire_form.py
  tests/app/forms/validation/test_single_date_range_validator.py
  tests/app/helpers/test_template_helpers.py
  tests/app/mock_data_store.py
  tests/app/questionnaire/test_dynamic_answer_options.py
  tests/app/questionnaire/test_questionnaire_store_updater.py
  tests/app/questionnaire/test_relationship_location.py
  tests/app/questionnaire/test_routing_path.py
  tests/app/questionnaire/test_when_rules.py
  tests/app/storage/test_datastore.py
  tests/app/submitter/test_submitter.py
  tests/app/views/contexts/summary/test_question.py
  tests/functional/generate_pages.py
  tests/integration/integration_test_case.py
  tests/integration/routes/test_questionnaire.py
  tests/integration/test_app_create.py
Labels: Bug Fix

#1031 BUG: Fixing schema validation failure on large errors
  scripts/validate_test_schemas.sh
Labels: Bug Fix

#1042 Bug: Context for health theme is incorrect
  app/translations/messages.pot
  app/views/contexts/submission_metadata_context.py
  app/views/contexts/thank_you_context.py
  app/views/contexts/view_submitted_response_context.py
  schemas/test/en/test_theme_health.json
  schemas/test/en/test_theme_social.json
  tests/app/views/contexts/test_submission_metatdata_context.py
  tests/app/views/contexts/test_submitted_response_context.py
  tests/app/views/contexts/test_thank_you_context.py
Labels: Bug Fix
