Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2023-07, with the labels that each got.

#1159 Bug Fix: None language code defaults to "en"
  app/routes/session.py
  tests/integration/create_token.py
  tests/integration/questionnaire/test_questionnaire_locale.py
Labels: Bug Fix

#1157 Looping 4 - Calculated Summary with repeating blocks
  app/questionnaire/placeholder_renderer.py
  app/questionnaire/questionnaire_schema.py
  app/questionnaire/questionnaire_store_updater.py
  app/questionnaire/schema_utils.py
  app/questionnaire/value_source_resolver.py
  app/views/contexts/list_context.py
  app/views/contexts/section_summary_context.py
  app/views/contexts/summary/answer.py
  app/views/contexts/summary/block.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary/list_collector_block.py
  app/views/contexts/summary/question.py
  app/views/handlers/list_action.py
  app/views/handlers/list_collector.py
  app/views/handlers/list_edit_question.py
  app/views/handlers/list_repeating_question.py
  app/views/handlers/question.py
  schemas/test/en/test_new_calculated_summary_repeating_blocks.json
  tests/app/questionnaire/conftest.py
  tests/app/questionnaire/rules/test_rule_evaluator.py
  tests/app/questionnaire/test_dynamic_answer_options.py
  tests/app/questionnaire/test_placeholder_renderer.py
  tests/app/questionnaire/test_value_source_resolver.py
  tests/app/views/contexts/conftest.py
  tests/app/views/contexts/summary/test_answer.py
  tests/app/views/contexts/test_calculated_summary_context.py
  tests/app/views/contexts/test_section_summary_context.py
  tests/functional/base_pages/calculated-summary.page.js
  tests/functional/helpers.js
  tests/functional/spec/features/calculated_summary/new_calculated_summary_repeating_and_static_answers.spec.js
  tests/functional/spec/features/calculated_summary/new_calculated_summary_repeating_blocks.spec.js
  tests/functional/spec/features/repeating_blocks/list_collector_repeating_blocks.spec.js
  tests/functional/spec/list_collector_section_summary.spec.js
  tests/integration/questionnaire/__init__.py
  tests/integration/questionnaire/test_questionnaire_calculated_summary.py
  tests/integration/questionnaire/test_questionnaire_list_collector_repeating_blocks.py
Labels: New Feature

#1094 Make placeholders to take into account answers on a path
  app/data_models/progress_store.py
  app/forms/questionnaire_form.py
  app/questionnaire/dependencies.py
  app/questionnaire/placeholder_parser.py
  app/questionnaire/questionnaire_schema.py
  app/questionnaire/questionnaire_store_updater.py
  app/questionnaire/router.py
  app/questionnaire/value_source_resolver.py
  app/utilities/mappings.py
  app/utilities/types.py
  schemas/test/en/test_placeholder_first_non_empty_item.json
  schemas/test/en/test_placeholder_first_non_empty_item_cross_section_dependencies.json
  schemas/test/en/test_placeholder_first_non_empty_item_repeating_sections.json
  tests/app/questionnaire/test_placeholder_parser.py
  tests/app/views/contexts/test_summary_context.py
  tests/functional/spec/placeholder_answers_on_the_path.spec.js
Labels: Enhancement
