Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2023-05, with the labels that each got.

#1089 Update MAX_NUMBERS to 15 digits
  app/settings.py
  schemas/test/en/test_currency.json
  schemas/test/en/test_numbers.json
  schemas/test/en/test_unit_patterns.json
  tests/app/forms/test_questionnaire_form.py
  tests/app/test_jinja_filters.py
  tests/functional/spec/numbers.spec.js
  tests/integration/questionnaire/test_questionnaire_html_escaping.py
  tests/integration/routes/test_thank_you.py
Labels: Enhancement

#1091 Update summaries to allow support for repeating sections
  app/jinja_filters.py
  app/translations/messages.pot
  app/views/contexts/section_summary_context.py
  app/views/contexts/submit_questionnaire_context.py
  app/views/contexts/summary/group.py
  app/views/contexts/summary_context.py
  app/views/contexts/view_submitted_response_context.py
  schemas/test/en/test_list_collector_section_summary.json
  schemas/test/en/test_view_submitted_response_repeating_sections.json
  templates/partials/summary/summary.html
  tests/app/test_jinja_filters.py
  tests/app/views/contexts/test_summary_context.py
  tests/functional/spec/features/view_submitted_response/view_submitted_response.spec.js
  tests/functional/spec/list_collector_section_summary.spec.js
Labels: New Feature

#1102 Fix rendering on Summary pages
  .design-system-version
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/section_summary_context.py
  app/views/contexts/summary_context.py
  schemas/test/en/test_view_submitted_response.json
  templates/partials/summary/collapsible-summary.html
  templates/partials/summary/summary.html
  templates/sectionsummary.html
  tests/app/views/contexts/__init__.py
  tests/app/views/contexts/test_calculated_summary_context.py
  tests/app/views/contexts/test_section_summary_context.py
  tests/app/views/contexts/test_submitted_response_context.py
  tests/app/views/contexts/test_summary_context.py
Labels: Bug Fix

#1104 Make response expiry date mandatory
  app/data_models/metadata_proxy.py
  app/data_models/questionnaire_store.py
  app/utilities/metadata_parser.py
  app/utilities/metadata_parser_v2.py
  tests/app/data_model/conftest.py
  tests/app/data_model/test_metadata_proxy.py
  tests/app/parser/conftest.py
  tests/app/submitter/conftest.py
  tests/app/views/handlers/conftest.py
  tests/app/views/handlers/test_individual_response_fulfilment_request.py
  tests/app/views/handlers/test_question_with_dynamic_answers.py
  tests/functional/jwt_helper.js
  tests/integration/create_token.py
  tests/integration/routes/test_errors.py
  tests/integration/routes/test_jwt_authentication.py
  tests/integration/test_flush_data.py
Labels: Enhancement

#1044 Implement "progress" value source
  Pipfile
  Pipfile.lock
  app/data_models/progress_store.py
  app/jinja_filters.py
  app/publisher/publisher.py
  app/questionnaire/dependencies.py
  app/questionnaire/path_finder.py
  app/questionnaire/placeholder_parser.py
  app/questionnaire/placeholder_transforms.py
  app/questionnaire/questionnaire_schema.py
  app/questionnaire/questionnaire_store_updater.py
  app/questionnaire/router.py
  app/questionnaire/rules/rule_evaluator.py
  app/questionnaire/value_source_resolver.py
  app/survey_config/business_config.py
  app/survey_config/social_survey_config.py
  app/survey_config/survey_config.py
  app/translations/messages.pot
  app/utilities/mappings.py
  app/views/contexts/calculated_summary_context.py
  app/views/contexts/summary/answer.py
  app/views/handlers/calculated_summary.py
  app/views/handlers/individual_response.py
  app/views/handlers/list_action.py
  app/views/handlers/question.py
  schemas/test/en/test_progress_block_value_source_repeating_sections.json
  schemas/test/en/test_progress_section_value_source_repeating_sections.json
  schemas/test/en/test_progress_value_source_blocks.json
  schemas/test/en/test_progress_value_source_blocks_cross_section.json
  schemas/test/en/test_progress_value_source_calculated_summary.json
  schemas/test/en/test_progress_value_source_calculated_summary_extended.json
  schemas/test/en/test_progress_value_source_repeating_sections_chained_dependencies.json
  schemas/test/en/test_progress_value_source_section_enabled_hub.json
  schemas/test/en/test_progress_value_source_section_enabled_hub_complex.json
  schemas/test/en/test_progress_value_source_section_enabled_no_hub.json
  tests/app/data_model/test_progress_store.py
  tests/app/data_model/test_questionnaire_store.py
  tests/app/questionnaire/conftest.py
  tests/app/questionnaire/rules/test_rule_evaluator.py
  tests/app/questionnaire/test_placeholder_parser.py
  tests/app/questionnaire/test_questionnaire_schema.py
  tests/app/questionnaire/test_questionnaire_store_updater.py
  tests/app/questionnaire/test_value_source_resolver.py
  tests/app/views/contexts/summary/test_question.py
  tests/functional/spec/features/progress/progress_value_source_blocks.js
  tests/functional/spec/features/progress/progress_value_source_repeating.js
  tests/integration/integration_test_case.py
  tests/integration/questionnaire/test_questionnaire_progress_value_source_blocks.py
  tests/integration/questionnaire/test_questionnaire_progress_value_source_calculated_summary.py
  tests/integration/questionnaire/test_questionnaire_progress_value_source_in_repeating_sections.py
  tests/integration/questionnaire/test_questionnaire_progress_value_source_section_enabled.py
  tests/integration/test_application_variables.py
Labels: New Feature
