Repository ONSdigital/eq-questionnaire-runner, pull requests merged in 2024-01, with the labels that each got.

#1277 Update a schema to demonstrate minimum/maximum supports floats
  app/jinja_filters.py
  app/questionnaire/questionnaire_schema.py
  app/translations/messages.pot
  schemas/test/en/test_metadata_routing.json
  schemas/test/en/test_numbers.json
  tests/app/forms/test_questionnaire_form.py
  tests/functional/spec/numbers.spec.js
Labels: dont merge

#1283 Migrate to GA4
  README.md
  app/helpers/template_helpers.py
  app/settings.py
  app/setup.py
  app/translations/messages.pot
  ci/deploy_app.sh
  templates/layouts/_base.html
  tests/app/helpers/test_template_helpers.py
  tests/integration/test_app_create.py
  tests/integration/test_application_variables.py
Labels: Breaking Change

#1300 Reintroduce unsafe-inline keyword to style-src of CSP policy
  app/setup.py
  tests/integration/test_app_create.py
Labels: Bug Fix

#1306 Bug fix: Backwards routing does not work when dependencies exist
  app/questionnaire/path_finder.py
  schemas/test/en/test_confirmation_question_backwards_routing.json
  tests/app/questionnaire/test_path_finder.py
Labels: Bug Fix

#1309 Allow the hub to be enabled with repeating sections
  app/questionnaire/router.py
  schemas/test/en/test_hub_section_required_with_repeat.json
  schemas/test/en/test_hub_section_required_with_repeat_supplementary.json
  tests/app/questionnaire/test_router.py
  tests/functional/spec/features/hub_and_spoke/hub_and_spoke.spec.js
  tests/integration/questionnaire/test_questionnaire_hub.py
Labels: New Feature
